import { Activity, ArrowRight, BarChart3, Check, Dumbbell, Users, ShoppingCart, Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { useTranslation } from 'react-i18next'
import { LanguageSwitcher } from '../components/LanguageSwitcher'
import { GlassCard, NeonButton } from '../components/ui'
import { useAuth } from '../contexts/AuthContext'

export function LandingPage() {
  const { t } = useTranslation()
  const { user } = useAuth()
  const destination = user ? '/app' : '/login'
  const features = [
    { icon: Dumbbell, title: t('landing.train'), text: t('landing.live') },
    { icon: Activity, title: t('landing.eat'), text: t('nutrition.subtitle') },
    { icon: BarChart3, title: t('landing.planWeek'), text: t('strategy.subtitle') },
    { icon: ShoppingCart, title: t('landing.shop'), text: t('nutrition.grocerySubtitle') },
    { icon: Users, title: t('landing.doItTogether'), text: t('household.subtitle') },
  ]
  return <div className="landing-shell">
    <header className="public-header"><Link to="/" className="public-brand"><span className="brand-mark"><Dumbbell size={16} /></span><strong>train<span>together</span></strong></Link><div className="public-header-right"><LanguageSwitcher compact />{user ? <Link to="/app">{t('nav.overview')}</Link> : <Link to="/login">{t('landing.signIn')}</Link>}</div></header>
    <main>
      <section className="landing-hero"><div className="landing-hero-copy"><span className="landing-eyebrow"><i />{t('landing.eyebrow')}</span><motion.h1 initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }}>{t('landing.titleOne')}<span>{t('landing.titleTwo')}</span></motion.h1><p>{t('landing.subtitle')}</p><div className="landing-actions"><Link to={destination}><NeonButton size="lg">{t('landing.cta')} <ArrowRight size={16} /></NeonButton></Link><Link to="/login" className="neon-button neon-button-ghost neon-button-lg">{t('landing.seeHow')}</Link></div><div className="landing-footnote"><span className="avatar-wrap avatar-xs"><span className="avatar"><span>F</span></span></span><span className="avatar-wrap avatar-xs"><span className="avatar" style={{ background: 'linear-gradient(145deg,#db5ddc,#7a58d4)' }}><span>M</span></span></span><span>{t('landing.proof')}</span></div></div><div className="landing-visual" aria-label="Train Together dashboard preview"><div className="visual-glow" /><motion.div className="dashboard-preview" initial={{ opacity: 0, y: 25, rotateY: -7 }} animate={{ opacity: 1, y: 0, rotateY: -7 }} transition={{ delay: .2, duration: .75 }}><div className="preview-bar"><i /><i /><i /></div><div className="preview-body"><div className="preview-side"><strong>tt.</strong><span /><span /><span /><span /><span /></div><div className="preview-main"><div className="preview-greet" /><div className="preview-sub" /><div className="preview-rings"><div className="preview-stat-big"><div className="fake-ring" /><div className="preview-lines"><i /><i /><i /></div></div><div className="preview-stat-small"><i /><b /></div></div><div className="preview-workout"><div className="preview-workout-head"><i /><b /></div><div className="preview-exercises"><span /><span /><span /><span /></div></div></div></div></motion.div><div className="preview-floating"><span className="floating-check"><Check size={14} /></span><div><strong>{t('landing.everythingYouNeed')}</strong><span>{t('landing.onePlan')}</span></div></div></div></section>

      <section className="landing-section"><div className="landing-section-head"><span className="eyebrow-label">{t('landing.findPeople')}</span><h2>{t('landing.findPeopleSub')}</h2></div><GlassCard className="find-people-mockup" style={{ maxWidth: 450, margin: '0 auto', textAlign: 'center', padding: 30 }}><div style={{ display: 'flex', alignItems: 'center', background: 'rgba(255,255,255,0.05)', borderRadius: 12, padding: '10px 15px', border: '1px solid rgba(255,255,255,0.1)', marginBottom: 20 }}><Search size={16} color="#8e829d" style={{ marginRight: 10 }} /><span style={{ color: '#8e829d', fontSize: 14 }}>{t('landing.searchPrompt')}</span></div><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: 15, background: 'rgba(255,255,255,0.03)', borderRadius: 12, border: '1px solid rgba(255,255,255,0.05)' }}><div style={{ display: 'flex', alignItems: 'center', gap: 12 }}><span className="avatar-wrap avatar-sm"><span className="avatar" style={{ background: 'linear-gradient(145deg,#db5ddc,#7a58d4)' }}><span>M</span></span></span><div style={{ textAlign: 'left' }}><strong style={{ display: 'block', fontSize: 15, color: '#fff' }}>María</strong><span style={{ fontSize: 13, color: '#8e829d' }}>@maria</span></div></div><NeonButton size="sm" variant="secondary">Add</NeonButton></div></GlassCard></section>

      <section className="landing-section"><div className="landing-section-head"><span className="eyebrow-label">{t('landing.betterTogether')}</span><h2>{t('landing.findAndTurn')}</h2><p>{t('landing.betterTogetherText')}</p></div><div className="feature-grid">{features.map(({ icon: Icon, title, text }) => <GlassCard key={title} className="feature-card" hover><div className="feature-icon"><Icon size={17} /></div><h3>{title}</h3><p>{text}</p></GlassCard>)}</div></section>

      <section className="landing-section" style={{ paddingTop: 30 }}><div className="landing-section-head"><h2>{t('landing.pricing')}</h2></div><div className="pricing-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 20, maxWidth: 900, margin: '0 auto' }}>
        <GlassCard className="pricing-card" style={{ padding: 30, display: 'flex', flexDirection: 'column' }}><h3>{t('landing.priceFree')}</h3><div style={{ fontSize: 36, fontWeight: 700, margin: '15px 0' }}>$0</div><ul style={{ listStyle: 'none', padding: 0, margin: '20px 0', fontSize: 14, color: '#b2a5c4', flex: 1 }}><li style={{ marginBottom: 10 }}>✓ {t('landing.individualPlanning')}</li><li style={{ marginBottom: 10 }}>✓ {t('landing.exerciseLibrary')}</li><li>✓ {t('landing.foodLog')}</li></ul><NeonButton size="lg" variant="secondary" style={{ width: '100%' }}>{t('landing.cta')}</NeonButton></GlassCard>
        <GlassCard className="pricing-card" style={{ padding: 30, display: 'flex', flexDirection: 'column', border: '1px solid #7a58d4' }}><div style={{ display: 'inline-block', background: '#7a58d4', color: '#fff', fontSize: 10, fontWeight: 700, padding: '4px 8px', borderRadius: 20, marginBottom: 10, alignSelf: 'flex-start' }}>{t('landing.popular')}</div><h3>{t('landing.priceDuo')}</h3><div style={{ fontSize: 36, fontWeight: 700, margin: '15px 0' }}>$11.99<span style={{ fontSize: 14, fontWeight: 400, color: '#8e829d' }}>/{t('landing.mo')}</span></div><ul style={{ listStyle: 'none', padding: 0, margin: '20px 0', fontSize: 14, color: '#b2a5c4', flex: 1 }}><li style={{ marginBottom: 10 }}>✓ {t('landing.everythingFree')}</li><li style={{ marginBottom: 10 }}>✓ {t('landing.sharedHousehold')}</li><li style={{ marginBottom: 10 }}>✓ {t('landing.sharedGrocery')}</li><li>✓ {t('landing.advancedInsights')}</li></ul><NeonButton size="lg" style={{ width: '100%' }}>{t('landing.cta')}</NeonButton></GlassCard>
      </div></section>
    </main>
    <footer className="landing-footer"><span>© 2026 Train Together</span><span>{t('landing.proof')}</span></footer>
  </div>
}
