import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import { LANGUAGE_KEY, readStorage } from './lib/storage'

const resources = {
  en: {
    translation: {
      appName: 'Train Together',
      tagline: 'Train together. Grow together.',
      nav: { overview: 'Overview', strategy: 'Strategy', live: 'Live training', quickLog: 'Quick log', progress: 'Progress', history: 'History', couple: 'Our progress', exercises: 'Exercise library', profile: 'Profile' },
      landing: { eyebrow: 'Your private fitness space', titleOne: 'Train together.', titleTwo: 'Grow together.', subtitle: 'Your training. Your progress. Your shared evolution.', cta: 'Start your journey', signIn: 'Sign in', proof: 'Built for two. Designed to keep momentum.', live: 'Live training', plan: 'Your plan, made visible', analytics: 'Progress that feels personal', shared: 'A shared space for every win' },
      auth: { welcome: 'Welcome back', subtitle: 'Pick up where you left off.', username: 'Username', password: 'Password', usernamePlaceholder: 'e.g. fabricio', passwordPlaceholder: 'Your password', submit: 'Enter your space', back: 'Back to home', demoHint: 'Demo access', invalid: 'Those credentials do not match our records.', configured: 'Connected to Supabase', local: 'Local demo mode', fabricio: 'Fabricio', maria: 'María', credentialsHint: 'Use the credentials documented in README for the local preview.' },
      common: { today: 'Today', save: 'Save changes', cancel: 'Cancel', close: 'Close', edit: 'Edit', add: 'Add', remove: 'Remove', delete: 'Delete', search: 'Search', loading: 'Loading', viewAll: 'View all', kg: 'kg', reps: 'reps', min: 'min', sets: 'sets', week: 'week', of: 'of', complete: 'Complete', previous: 'Previous', next: 'Next', noData: 'No data yet', all: 'All', back: 'Back', confirm: 'Confirm', new: 'New', online: 'Live sync', local: 'Local preview', clear: 'Clear', exercises: 'exercises', exercise: 'Exercise', seconds: 'sec', bodyWeight: 'Body weight' },
      dashboard: { goodMorning: 'Good morning, {{name}}', overview: 'Here’s your training pulse for today.', dailyProgress: 'Daily progress', steps: 'Steps', calories: 'Calories', target: 'target', todayWorkout: 'Today’s workout', noWorkout: 'No workout planned today', startLive: 'Start live training', manual: 'Log manually', estimated: 'Estimated', consistency: 'Consistency', thisWeek: 'this week', streak: 'day streak', volume: 'Training volume', activity: 'Couple activity', seeProgress: 'See progress', newRecord: 'New personal record', completed: 'completed', stepGoal: 'reached their step goal', keepGoing: 'Keep the rhythm going.', trainingReady: 'Your next session is ready.' },
      strategy: { title: 'Strategy', subtitle: 'The plan behind your progress.', nutrition: 'Nutrition targets', activity: 'Activity targets', calories: 'Calories', protein: 'Protein', carbs: 'Carbs', fats: 'Fats', fiber: 'Fiber', steps: 'Daily steps', workouts: 'Workouts / week', minutes: 'Active minutes', trainingPlan: 'Training plan', trainingPlanSubtitle: 'Shape the week around how you want to feel.', addDay: 'Add training day', addExercise: 'Add exercise', editNutrition: 'Edit nutrition', renameDay: 'Rename day', removeDay: 'Remove day', emptyDay: 'This day is ready for a plan.', chooseExercise: 'Choose an exercise', rest: 'Rest', notes: 'Notes', dayName: 'Day name', description: 'Description', noExercises: 'No exercises yet', strategySaved: 'Strategy updated', schedule: 'Weekly schedule' },
      live: { title: 'Live training', subtitle: 'One set at a time.', choose: 'Choose a workout', chooseSubtitle: 'Follow the plan or start with a different day.', ready: 'Ready when you are.', start: 'Start session', exercise: 'Exercise', set: 'Set', planned: 'Planned', actual: 'Actual', weight: 'Weight', reps: 'Reps', difficulty: 'RPE / difficulty', feeling: 'Feeling', pain: 'Pain', notes: 'Notes', completeSet: 'Complete set', rest: 'Rest', restReady: 'Rest when you need it.', continue: 'Continue', pause: 'Pause', skip: 'Skip', addTime: '+15 sec', reduceTime: '-15 sec', workoutComplete: 'Workout complete', review: 'A strong session in the books.', duration: 'Duration', totalVolume: 'Total volume', totalReps: 'Total reps', howWas: 'How was your workout?', energy: 'Energy', fatigue: 'Fatigue', mood: 'Mood', overall: 'Overall feeling', finish: 'Finish workout', resumeTitle: 'You have an unfinished workout', resume: 'Resume session', discard: 'Discard', noRest: 'Rest without a timer', noRestDescription: 'Continue when you’re ready.', excellent: 'Excellent', good: 'Good', neutral: 'Neutral', bad: 'Bad', veryBad: 'Very bad', setSaved: 'Set saved', viewExercise: 'View exercise details' },
      progress: { title: 'Progress', subtitle: 'Small signals. Real momentum.', range: 'Time range', days7: '7 days', days30: '30 days', months3: '3 months', months6: '6 months', allTime: 'All time', volume: 'Training volume', volumeHint: 'Load moved across completed sets', steps: 'Steps', bodyWeight: 'Body weight', workouts: 'Workouts', rpe: 'RPE trend', adherence: 'Strategy adherence', workoutAdherence: 'Workout adherence', stepGoal: 'Step goal', plannedActual: 'Planned vs actual', plannedLoad: 'Planned load', actualLoad: 'Actual load', records: 'Personal records', maxWeight: 'Max weight', bestSet: 'Best set', maxReps: 'Max reps', fromYourData: 'Calculated from your logged data' },
      history: { title: 'History', subtitle: 'Your work, kept in view.', completed: 'Completed', abandoned: 'Abandoned', duration: 'Duration', volume: 'Volume', feeling: 'Feeling', details: 'Session details', noSessions: 'Your completed sessions will show up here.' },
      couple: { title: 'Our progress', subtitle: 'Better together, never against each other.', weekly: 'This week', lifetime: 'All time', workouts: 'Workouts', steps: 'Steps', records: 'PRs', streak: 'Streak', activity: 'Activity feed', shared: 'Shared momentum', sync: 'Updates appear here as they happen.', noEvents: 'Your shared activity will appear here.' },
      exercises: { title: 'Exercise library', subtitle: 'Find the right movement for your plan.', searchPlaceholder: 'Search exercises', muscle: 'Muscle group', equipment: 'Equipment', allMuscles: 'All muscles', allEquipment: 'All equipment', instructions: 'Instructions', source: 'Dataset source', addToPlan: 'Add to plan', added: 'Added to plan', details: 'Exercise details', dataset: 'Exercises dataset' },
      quick: { title: 'Quick log', subtitle: 'Capture the whole session without breaking your rhythm.', workout: 'Workout', setsDone: 'Sets completed', save: 'Save workout', required: 'Add at least one completed set before saving.', activeHint: 'Finish or resume your active Live Training session first.', viewExercise: 'View exercise details', finishEyebrow: 'Session notes', finishTitle: 'Anything worth remembering?', finishDescription: 'Add a note for your future self.' },
      share: { button: 'Share image', title: 'Share your momentum', subtitle: 'A snapshot made to celebrate the work.', download: 'Download image', native: 'Share', baseHint: 'Add a base image at public/share to customize this template.', generated: 'Image ready' },
      profile: { title: 'Profile', subtitle: 'Keep your numbers and preferences current.', personal: 'Personal details', name: 'Display name', height: 'Height', weight: 'Weight', goals: 'Daily goals', language: 'Language', languageHint: 'Choose how the app speaks to you.', signOut: 'Sign out', saved: 'Profile updated' },
      errors: { save: 'Could not save your changes. Try again.', required: 'Please complete the required fields.' },
      days: { monday: 'Monday', tuesday: 'Tuesday', wednesday: 'Wednesday', thursday: 'Thursday', friday: 'Friday', saturday: 'Saturday', sunday: 'Sunday' },
      feelings: { one: 'Very bad', two: 'Bad', three: 'Neutral', four: 'Good', five: 'Excellent' },
    },
  },
  es: {
    translation: {
      appName: 'Train Together', tagline: 'Entrenen juntos. Crezcan juntos.', nav: { overview: 'Resumen', strategy: 'Estrategia', live: 'Entrenamiento en vivo', quickLog: 'Registro rápido', progress: 'Progreso', history: 'Historial', couple: 'Nuestro progreso', exercises: 'Biblioteca', profile: 'Perfil' },
      landing: { eyebrow: 'Tu espacio privado de fitness', titleOne: 'Entrenen juntos.', titleTwo: 'Crezcan juntos.', subtitle: 'Tu entrenamiento. Tu progreso. Nuestra evolución.', cta: 'Comenzar', signIn: 'Iniciar sesión', proof: 'Creado para dos. Diseñado para mantener el ritmo.', live: 'Entrenamiento en vivo', plan: 'Tu plan, siempre visible', analytics: 'Progreso que se siente personal', shared: 'Un espacio para cada logro' },
      auth: { welcome: 'Bienvenido de nuevo', subtitle: 'Retoma desde donde lo dejaste.', username: 'Usuario', password: 'Contraseña', usernamePlaceholder: 'ej. fabricio', passwordPlaceholder: 'Tu contraseña', submit: 'Entrar a mi espacio', back: 'Volver al inicio', demoHint: 'Acceso demo', invalid: 'Esos datos no coinciden con nuestros registros.', configured: 'Conectado a Supabase', local: 'Modo demo local', fabricio: 'Fabricio', maria: 'María', credentialsHint: 'Usa las credenciales documentadas en el README para la vista local.' },
      common: { today: 'Hoy', save: 'Guardar cambios', cancel: 'Cancelar', close: 'Cerrar', edit: 'Editar', add: 'Agregar', remove: 'Quitar', delete: 'Eliminar', search: 'Buscar', loading: 'Cargando', viewAll: 'Ver todo', kg: 'kg', reps: 'reps', min: 'min', sets: 'series', week: 'semana', of: 'de', complete: 'Completo', previous: 'Anterior', next: 'Siguiente', noData: 'Todavía no hay datos', all: 'Todos', back: 'Volver', confirm: 'Confirmar', new: 'Nuevo', online: 'Sincronización activa', local: 'Vista local', clear: 'Limpiar', exercises: 'ejercicios', exercise: 'Ejercicio', seconds: 'seg', bodyWeight: 'Peso corporal' },
      dashboard: { goodMorning: 'Buenos días, {{name}}', overview: 'Este es tu pulso de entrenamiento de hoy.', dailyProgress: 'Progreso del día', steps: 'Pasos', calories: 'Calorías', target: 'objetivo', todayWorkout: 'Entrenamiento de hoy', noWorkout: 'No hay entrenamiento planificado hoy', startLive: 'Empezar en vivo', manual: 'Cargar manualmente', estimated: 'Estimado', consistency: 'Constancia', thisWeek: 'esta semana', streak: 'días seguidos', volume: 'Volumen de entrenamiento', activity: 'Actividad de pareja', seeProgress: 'Ver progreso', newRecord: 'Nuevo récord personal', completed: 'completó', stepGoal: 'alcanzó su objetivo de pasos', keepGoing: 'Mantén el ritmo.', trainingReady: 'Tu próxima sesión está lista.' },
      strategy: { title: 'Estrategia', subtitle: 'El plan detrás de tu progreso.', nutrition: 'Objetivos nutricionales', activity: 'Objetivos de actividad', calories: 'Calorías', protein: 'Proteínas', carbs: 'Carbohidratos', fats: 'Grasas', fiber: 'Fibra', steps: 'Pasos diarios', workouts: 'Entrenamientos / semana', minutes: 'Minutos activos', trainingPlan: 'Plan de entrenamiento', trainingPlanSubtitle: 'Diseña la semana según cómo quieres sentirte.', addDay: 'Agregar día', addExercise: 'Agregar ejercicio', editNutrition: 'Editar nutrición', renameDay: 'Renombrar día', removeDay: 'Eliminar día', emptyDay: 'Este día está listo para recibir un plan.', chooseExercise: 'Elegir un ejercicio', rest: 'Descanso', notes: 'Notas', dayName: 'Nombre del día', description: 'Descripción', noExercises: 'Todavía no hay ejercicios', strategySaved: 'Estrategia actualizada', schedule: 'Agenda semanal' },
      live: { title: 'Entrenamiento en vivo', subtitle: 'Una serie a la vez.', choose: 'Elegir entrenamiento', chooseSubtitle: 'Sigue el plan o empieza otro día.', ready: 'Listo cuando tú estés.', start: 'Empezar sesión', exercise: 'Ejercicio', set: 'Serie', planned: 'Planificado', actual: 'Real', weight: 'Peso', reps: 'Repeticiones', difficulty: 'RPE / dificultad', feeling: 'Sensación', pain: 'Dolor', notes: 'Notas', completeSet: 'Completar serie', rest: 'Descanso', restReady: 'Descansa lo que necesites.', continue: 'Continuar', pause: 'Pausar', skip: 'Saltar', addTime: '+15 seg', reduceTime: '-15 seg', workoutComplete: 'Entrenamiento completo', review: 'Una gran sesión queda registrada.', duration: 'Duración', totalVolume: 'Volumen total', totalReps: 'Repeticiones totales', howWas: '¿Cómo fue tu entrenamiento?', energy: 'Energía', fatigue: 'Fatiga', mood: 'Ánimo', overall: 'Sensación general', finish: 'Finalizar entrenamiento', resumeTitle: 'Tienes un entrenamiento sin terminar', resume: 'Retomar sesión', discard: 'Descartar', noRest: 'Descanso sin contador', noRestDescription: 'Continúa cuando estés listo.', excellent: 'Excelente', good: 'Bien', neutral: 'Neutral', bad: 'Mal', veryBad: 'Muy mal', setSaved: 'Serie guardada', viewExercise: 'Ver detalle del ejercicio' },
      progress: { title: 'Progreso', subtitle: 'Pequeñas señales. Impulso real.', range: 'Rango de tiempo', days7: '7 días', days30: '30 días', months3: '3 meses', months6: '6 meses', allTime: 'Todo', volume: 'Volumen de entrenamiento', volumeHint: 'Carga movida en series completadas', steps: 'Pasos', bodyWeight: 'Peso corporal', workouts: 'Entrenamientos', rpe: 'Tendencia de RPE', adherence: 'Adherencia a la estrategia', workoutAdherence: 'Adherencia de entrenamientos', stepGoal: 'Objetivo de pasos', plannedActual: 'Planificado vs realizado', plannedLoad: 'Carga planificada', actualLoad: 'Carga real', records: 'Récords personales', maxWeight: 'Peso máximo', bestSet: 'Mejor serie', maxReps: 'Más repeticiones', fromYourData: 'Calculado a partir de tus registros' },
      history: { title: 'Historial', subtitle: 'Tu trabajo, siempre a la vista.', completed: 'Completado', abandoned: 'Abandonado', duration: 'Duración', volume: 'Volumen', feeling: 'Sensación', details: 'Detalle de sesión', noSessions: 'Tus sesiones completadas aparecerán aquí.' },
      couple: { title: 'Nuestro progreso', subtitle: 'Mejor juntos, nunca en competencia.', weekly: 'Esta semana', lifetime: 'Todo el tiempo', workouts: 'Entrenamientos', steps: 'Pasos', records: 'Récords', streak: 'Racha', activity: 'Actividad compartida', shared: 'Impulso compartido', sync: 'Las novedades aparecen aquí al instante.', noEvents: 'La actividad compartida aparecerá aquí.' },
      exercises: { title: 'Biblioteca de ejercicios', subtitle: 'Encuentra el movimiento ideal para tu plan.', searchPlaceholder: 'Buscar ejercicios', muscle: 'Grupo muscular', equipment: 'Equipamiento', allMuscles: 'Todos los músculos', allEquipment: 'Todo el equipamiento', instructions: 'Instrucciones', source: 'Fuente del dataset', addToPlan: 'Agregar al plan', added: 'Agregado al plan', details: 'Detalle del ejercicio', dataset: 'Exercises dataset' },
      quick: { title: 'Registro rápido', subtitle: 'Registra toda la sesión sin romper el ritmo.', workout: 'Entrenamiento', setsDone: 'Series completadas', save: 'Guardar entrenamiento', required: 'Agrega al menos una serie completada antes de guardar.', activeHint: 'Primero termina o retoma tu sesión de Entrenamiento en vivo.', viewExercise: 'Ver detalle del ejercicio', finishEyebrow: 'Notas de la sesión', finishTitle: '¿Algo que quieras recordar?', finishDescription: 'Deja una nota para tu yo del futuro.' },
      share: { button: 'Compartir imagen', title: 'Comparte tu impulso', subtitle: 'Una imagen para celebrar el trabajo.', download: 'Descargar imagen', native: 'Compartir', baseHint: 'Agrega una imagen base en public/share para personalizar esta plantilla.', generated: 'Imagen lista' },
      profile: { title: 'Perfil', subtitle: 'Mantén actualizados tus datos y preferencias.', personal: 'Datos personales', name: 'Nombre visible', height: 'Altura', weight: 'Peso', goals: 'Objetivos diarios', language: 'Idioma', languageHint: 'Elige cómo quieres que te hable la app.', signOut: 'Cerrar sesión', saved: 'Perfil actualizado' },
      errors: { save: 'No pudimos guardar tus cambios. Inténtalo de nuevo.', required: 'Completa los campos obligatorios.' },
      days: { monday: 'Lunes', tuesday: 'Martes', wednesday: 'Miércoles', thursday: 'Jueves', friday: 'Viernes', saturday: 'Sábado', sunday: 'Domingo' }, feelings: { one: 'Muy mal', two: 'Mal', three: 'Neutral', four: 'Bien', five: 'Excelente' },
    },
  },
}

const initialLanguage = readStorage<'en' | 'es'>(LANGUAGE_KEY, 'en')

void i18n.use(initReactI18next).init({
  resources,
  lng: initialLanguage,
  fallbackLng: 'en',
  interpolation: { escapeValue: false },
})

export default i18n
